meta_product_name: 'IMKAUFMANN'
meta_title: 'IMKAUFMANN'
meta_description: 'Personal photography portfolio for Guilherme Kaufmann'
meta_image: 'logo.png' # should exist in `app/assets/images/`
twitter_account: '@Timon_ala_carte' # required for Twitter Cards
